# Generated by Django 3.1.3 on 2020-11-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streets',
            options={},
        ),
    ]
