# Generated by Django 3.1.3 on 2020-11-16 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201116_1014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communities',
            options={},
        ),
    ]
