# Generated by Django 3.1.3 on 2020-11-16 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201116_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communities',
            name='district_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.districts', verbose_name='Район'),
        ),
    ]
