# Generated by Django 3.1.3 on 2020-11-16 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20201116_1020'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='communities',
            options={'verbose_name': 'Махалля', 'verbose_name_plural': 'Махалли'},
        ),
        migrations.AlterModelOptions(
            name='districts',
            options={'verbose_name': 'Район', 'verbose_name_plural': 'Районы'},
        ),
        migrations.AlterModelOptions(
            name='flats',
            options={},
        ),
        migrations.AlterModelOptions(
            name='houses',
            options={},
        ),
        migrations.AlterModelOptions(
            name='merchants',
            options={},
        ),
        migrations.AlterModelOptions(
            name='migrations',
            options={},
        ),
        migrations.AlterModelOptions(
            name='streetcommunities',
            options={},
        ),
    ]
