# Generated by Django 3.1.3 on 2020-11-16 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20201116_1025'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='houses',
            options={'verbose_name': 'Дом', 'verbose_name_plural': 'Дома'},
        ),
    ]
