# Generated by Django 3.1.3 on 2020-11-16 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201116_1030'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streets',
            options={'verbose_name': 'Улица', 'verbose_name_plural': 'Улицы'},
        ),
        migrations.AddField(
            model_name='streets',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.communities'),
        ),
    ]
