# Generated by Django 3.1.3 on 2020-11-16 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20201116_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='communities',
            old_name='name_uz',
            new_name='name_oz',
        ),
        migrations.RenameField(
            model_name='districts',
            old_name='name_uz',
            new_name='name_oz',
        ),
        migrations.RenameField(
            model_name='streets',
            old_name='extra_uz',
            new_name='extra_oz',
        ),
        migrations.RenameField(
            model_name='streets',
            old_name='name_uz',
            new_name='name_oz',
        ),
    ]
