# Generated by Django 3.1.3 on 2020-11-16 12:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201116_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streets',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.communities', verbose_name='Махалля'),
        ),
    ]
