# Generated by Django 3.1.3 on 2020-11-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201116_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streets',
            name='type',
            field=models.CharField(choices=[('street', 'улица'), ('massif', 'массив'), ('avenue', 'проспект'), ('passage', 'проезд/тупик/переулок'), ('quarter', 'квартал'), ('other', 'другое (поселок, шоссе, пр.)')], max_length=32, verbose_name='Тип'),
        ),
    ]
