# Generated by Django 3.1.3 on 2020-11-16 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20201116_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streets',
            name='tags',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
    ]
