# Generated by Django 3.1.3 on 2020-11-17 08:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201116_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='streets',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='streets',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Изменен'),
            preserve_default=False,
        ),
    ]
