# Generated by Django 3.1.3 on 2020-11-17 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20201117_1337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streets',
            old_name='type',
            new_name='street_type',
        ),
    ]
