# Generated by Django 3.1.3 on 2020-11-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201117_1729'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Communities',
            new_name='Community',
        ),
        migrations.RenameModel(
            old_name='Districts',
            new_name='District',
        ),
        migrations.RenameModel(
            old_name='Flats',
            new_name='Flat',
        ),
        migrations.RenameModel(
            old_name='Houses',
            new_name='House',
        ),
        migrations.RenameModel(
            old_name='Merchants',
            new_name='Merchant',
        ),
        migrations.RenameModel(
            old_name='MerchantOffers',
            new_name='MerchantOffer',
        ),
        migrations.RenameModel(
            old_name='Migrations',
            new_name='Migration',
        ),
        migrations.RenameModel(
            old_name='Streets',
            new_name='Street',
        ),
    ]
