# Generated by Django 3.1.3 on 2020-12-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20201119_1246'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name_ru'], name='communities_name_ru_6d9dd4_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name_oz'], name='communities_name_oz_4d38dd_idx'),
        ),
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['name_uz'], name='communities_name_uz_20963b_idx'),
        ),
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['number'], name='houses_number_e97a84_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['name_ru'], name='streets_name_ru_d00527_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['name_oz'], name='streets_name_oz_e2ed10_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['name_uz'], name='streets_name_uz_e78d8a_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['extra_ru'], name='streets_extra_r_f469a3_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['extra_oz'], name='streets_extra_o_5313f8_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['extra_uz'], name='streets_extra_u_6641d7_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['tags_ru'], name='streets_tags_ru_27179d_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['tags_oz'], name='streets_tags_oz_4c8c24_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['tags_uz'], name='streets_tags_uz_9c9876_idx'),
        ),
    ]
