# Generated by Django 3.1.3 on 2020-12-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20201219_1210'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['street'], name='houses_street__8914ef_idx'),
        ),
    ]
