# Generated by Django 3.1.3 on 2020-12-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20201219_1211'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='community',
            index=models.Index(fields=['district'], name='communities_distric_99ffb6_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['district'], name='streets_distric_f9cc88_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['street_type'], name='streets_street__025663_idx'),
        ),
    ]
