# Generated by Django 3.1.3 on 2020-12-19 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20201219_1215'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='street',
            name='streets_street__025663_idx',
        ),
    ]
