# Generated by Django 3.1.3 on 2020-12-19 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20201219_1216'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='street',
            name='streets_name_ru_d00527_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='streets_name_oz_e2ed10_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='streets_name_uz_e78d8a_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='streets_extra_r_f469a3_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='streets_extra_o_5313f8_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='streets_extra_u_6641d7_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='streets_tags_ru_27179d_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='streets_tags_oz_4c8c24_idx',
        ),
        migrations.RemoveIndex(
            model_name='street',
            name='streets_tags_uz_9c9876_idx',
        ),
        migrations.AddField(
            model_name='street',
            name='full_name_oz',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Тўлиқ ном'),
        ),
        migrations.AddField(
            model_name='street',
            name='full_name_ru',
            field=models.CharField(blank=True, max_length=4096, verbose_name='Полное название'),
        ),
        migrations.AddField(
            model_name='street',
            name='full_name_uz',
            field=models.CharField(blank=True, max_length=4096, verbose_name="To'liq nom"),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['full_name_ru'], name='streets_full_na_ca54d8_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['full_name_oz'], name='streets_full_na_77cf8f_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['full_name_uz'], name='streets_full_na_1e57df_idx'),
        ),
    ]
