# Generated by Django 3.1.3 on 2020-12-25 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_csvfilestoparse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CSVFilesToParse',
        ),
    ]
