# Generated by Django 3.1.3 on 2021-01-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_delete_csvfilestoparse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='community',
        ),
    ]
