# Generated by Django 3.1.3 on 2021-01-08 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20210108_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='streetcommunities',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.community'),
        ),
        migrations.AddField(
            model_name='streetcommunities',
            name='street',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.street'),
        ),
    ]
