# Generated by Django 3.1.3 on 2021-01-08 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20210108_1323'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='streetcommunities',
            options={'verbose_name': 'Махалля улицы', 'verbose_name_plural': 'Махалли улиц'},
        ),
        migrations.RemoveField(
            model_name='streetcommunities',
            name='community_id_val',
        ),
        migrations.RemoveField(
            model_name='streetcommunities',
            name='street_id_val',
        ),
    ]
