# Generated by Django 3.1.3 on 2021-01-18 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20210108_1510'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='house',
            index=models.Index(fields=['cadaster_code'], name='houses_cadaste_702029_idx'),
        ),
    ]
