# Generated by Django 3.1.3 on 2021-01-21 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_auto_20210118_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='community',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.community', verbose_name='Махалля'),
        ),
        migrations.AlterField(
            model_name='house',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.street', verbose_name='Улица'),
        ),
    ]
