# Generated by Django 3.1.3 on 2021-02-25 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20210121_2013'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flat',
            new_name='Aparment',
        ),
        migrations.AlterModelOptions(
            name='aparment',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
    ]
