# Generated by Django 3.1.3 on 2021-02-25 11:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20210225_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Создан'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='aparment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='Изменен'),
            preserve_default=False,
        ),
    ]
