# Generated by Django 3.1.3 on 2021-02-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20210225_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='aparment',
            name='entrance',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Подъезд'),
        ),
        migrations.AddField(
            model_name='aparment',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='aparment',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=13, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='aparment',
            name='passport_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата регистрации'),
        ),
        migrations.AddField(
            model_name='aparment',
            name='rooms',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Комнат'),
        ),
    ]
