# Generated by Django 3.1.3 on 2021-02-25 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20210225_1703'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aparment',
            new_name='Apartment',
        ),
    ]
