# Generated by Django 3.1.3 on 2021-02-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20210225_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Этаж'),
        ),
    ]
