# Generated by Django 3.1.3 on 2021-02-25 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_apartment_floor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='passport_date',
        ),
    ]
