# Generated by Django 3.1.3 on 2021-03-01 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0042_remove_apartment_passport_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='house',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apartments', to='main.house', verbose_name='Дом'),
        ),
    ]
