# Generated by Django 3.1.3 on 2021-03-05 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0044_privatehouse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privatehouse',
            name='apartment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.apartment', verbose_name='Квартира'),
        ),
    ]
