# Generated by Django 3.1.3 on 2021-03-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20210305_1758'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateProperty',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('apartment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.apartment', verbose_name='Квартира')),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.house', verbose_name='Дом')),
            ],
            options={
                'verbose_name': 'Частная собственность',
                'verbose_name_plural': 'Частная собственность (для поиска по жилым помещениям)',
                'unique_together': {('house', 'apartment')},
            },
        ),
    ]
