# Generated by Django 3.1.3 on 2021-03-10 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0046_privateproperty'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PrivateHouse',
        ),
    ]
