# Generated by Django 3.1.3 on 2021-03-24 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0047_delete_privatehouse'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='building_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь построек'),
        ),
        migrations.AddField(
            model_name='house',
            name='living_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Жилая площадь'),
        ),
        migrations.AddField(
            model_name='house',
            name='total_area',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь участка'),
        ),
    ]
