# Generated by Django 3.1.3 on 2021-03-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0048_auto_20210324_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год постройки'),
        ),
    ]
