# Generated by Django 3.1.3 on 2021-03-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0049_house_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='wall_type',
            field=models.CharField(choices=[('concrete', 'Бетон'), ('baked_brick', 'Жженый кирпич'), ('reinforced_concrete', 'Железобетон (панельный)'), ('wooden', 'Деревянный')], max_length=20, null=True),
        ),
    ]
