# Generated by Django 3.1.3 on 2021-07-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0050_house_wall_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='wall_type',
            field=models.CharField(blank=True, choices=[('concrete', 'Бетон'), ('baked_brick', 'Жженый кирпич'), ('reinforced_concrete', 'Железобетон (панельный)'), ('wooden', 'Деревянный')], max_length=20, null=True),
        ),
    ]
