# Generated by Django 3.1.3 on 2020-12-26 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='csvfilestoparse',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы для добавления в реестр'},
        ),
        migrations.AddField(
            model_name='csvfilestoparse',
            name='with_flats',
            field=models.BooleanField(default=True, verbose_name='Многоэтажный дом'),
            preserve_default=False,
        ),
    ]
