# Generated by Django 3.1.3 on 2020-12-26 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_auto_20201226_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesToParse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parsed', models.BooleanField(default=False, verbose_name='Добавлен в базу')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('with_flats', models.BooleanField(verbose_name='Многоэтажный дом')),
            ],
            options={
                'verbose_name': 'Файл',
                'verbose_name_plural': 'Файлы для добавления в реестр',
            },
        ),
        migrations.DeleteModel(
            name='CSVFilesToParse',
        ),
    ]
