# Generated by Django 3.1.3 on 2021-01-22 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20201226_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestoparse',
            name='errors',
            field=models.TextField(blank=True, null=True, verbose_name='Возникшие ошибки'),
        ),
    ]
