# Generated by Django 3.1.3 on 2021-07-08 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_filestoparse_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='filestoparse',
            name='in_progress',
            field=models.BooleanField(default=False, verbose_name='В процессе добавления'),
        ),
    ]
